### ISSUE TITLE
How to check Internet Connection in Background continuously even if App is Running or Not/Closed..

### ISSUE THREAD

**Issue by patelakshay13890** [raheemadamboev/check-internet-android#3]
How Check Internet Connection in Broadcast Receiver or Service Like as we do in Activity ?
But I need in Service or Broadcast Receiver..
Means I need to check Internet Connation in Background continuously even if App is Running or Not/Closed..
As on Internet Connectivity change I want to Sync My Data to Server so please help me out..!!
Thanks..

**Comment by raheemadamboev** [comment]
You can use Jetpack WorkManager for that purpose:

https://developer.android.com/topic/libraries/architecture/workmanager

Check out its constraints, it has constraint to execute the code when there is an internet connection from background.

Here is a good video about it, if you prefer video way of learning: https://www.youtube.com/watch?v=Psc2xyutE2U&t=6s
